/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package brainfuck

import java.io.File

fun main(args: Array<String>) {
    println("Starting at " + args[0])
    evalFile(File(args[0]))
}
